"""Language options and translations for the ResQSense interface."""

LANGUAGE_OPTIONS = [
    ("Portugues", "pt"),
    ("English", "en"),
    ("Espanol", "es"),
    ("Francais", "fr"),
    ("Deutsch", "de"),
    ("Italiano", "it"),
    ("Nederlands", "nl"),
    ("Svenska", "sv"),
    ("Norsk", "no"),
    ("Dansk", "da"),
    ("Suomi", "fi"),
    ("Polski", "pl"),
    ("Cesky", "cs"),
    ("Magyar", "hu"),
    ("Romana", "ro"),
    ("Turkce", "tr"),
    ("Greek", "el"),
    ("Russian", "ru"),
    ("Ukrainian", "uk"),
    ("Arabic", "ar"),
    ("Hebrew", "he"),
    ("Hindi", "hi"),
    ("Bengali", "bn"),
    ("Chinese", "zh"),
    ("Japanese", "ja"),
    ("Korean", "ko"),
    ("Indonesian", "id"),
    ("Vietnamese", "vi"),
    ("Thai", "th"),
    ("Malay", "ms"),
]

TRANSLATIONS = {
    "en": {
        "fire_station": "Fire Station:",
        "name_id": "Name/ID:",
        "nr_operationals": "Nr of Operationals:",
        "login": "Log in",
        "warning_title": "Warning",
        "warn_select_station": "Please select the Fire Station.",
        "warn_enter_leader_name": "Please enter the team leader Name/ID.",
        "warn_ops_integer": "The number of operationals must be an integer.",
        "warn_ops_between": "The number of operationals must be between 1 and 12.",
        "warn_ops_at_least_one": "Set at least 1 operational.",
        "operational": "Operational",
        "menu_edit": "Edit",
        "menu_resources": "Additional Resources",
        "menu_language": "Language",
        "session_name": "Name: {name}",
        "end_session": "End Session",
        "end_session_title": "End Session",
        "end_session_confirm": "Do you want to end the current session?",
        "add_operational_title": "Add Operational",
        "add_firefighter": "Add Firefighter",
        "warn_max_ops": "You reached the maximum of {max_ops} operationals.",
        "warn_fill_all": "Please fill all fields!",
        "critical_alert_title": "Critical Alert",
        "man_down": "MAN DOWN !!!!",
        "is_down": "{name} is down!!",
        "reason": "Reason: {reason}",
        "view_more": "View More",
        "captain": "Captain",
        "fire_station_value": "Fire Station: {station}",
        "warnings": "Warnings",
        "no_warnings": "No warnings registered yet.",
        "reason_hr_high": "Rapid Heart Rate",
        "reason_spo2_low": "Low Blood Oxygenation",
        "reason_temp_high": "High Temperature",
        "reason_poor_connection": "Poor connection",
        "reason_fall": "Fall",
        "reason_critical_generic": "Critical condition detected",
        "altitude": "Altitude",
        "distance": "Distance",
        "coordinates": "Coordinates",
        "language_title": "Language",
        "language_select": "Select language:",
        "language_current": "Current: {language}",
        "language_apply": "Apply",
        "language_cancel": "Cancel",
    },
    "pt": {
        "fire_station": "Fire Station:",
        "name_id": "Name/ID:",
        "nr_operationals": "Nr of Operacionais:",
        "login": "Entrar",
        "warning_title": "Aviso",
        "warn_select_station": "Por favor, selecione a Fire Station.",
        "warn_enter_leader_name": "Por favor, introduza o Name/ID do Chefe de Equipa.",
        "warn_ops_integer": "O numero de operacionais deve ser um valor inteiro.",
        "warn_ops_between": "O numero de operacionais deve estar entre 1 e 12.",
        "warn_ops_at_least_one": "Defina pelo menos 1 operacional.",
        "operational": "Operacional",
        "menu_edit": "Editar",
        "menu_resources": "Recursos Adicionais",
        "menu_language": "Lingua",
        "session_name": "Nome: {name}",
        "end_session": "Terminar Sessao",
        "end_session_title": "Terminar Sessao",
        "end_session_confirm": "Queres terminar a sessao atual?",
        "add_operational_title": "Adicionar Operacional",
        "add_firefighter": "Adicionar Bombeiro",
        "warn_max_ops": "Atingiu o numero maximo de {max_ops} operacionais.",
        "warn_fill_all": "Preencha todos os campos!",
        "critical_alert_title": "Alerta Critico",
        "man_down": "HOMEM CAIDO !!!!",
        "is_down": "{name} esta em baixo!!",
        "reason": "Razao: {reason}",
        "view_more": "Ver Mais",
        "captain": "Capitao",
        "fire_station_value": "Estacao: {station}",
        "warnings": "Avisos",
        "no_warnings": "Sem avisos registados.",
        "reason_hr_high": "Ritmo Cardiaco Rapido",
        "reason_spo2_low": "Baixa Oxigenacao no Sangue",
        "reason_temp_high": "Temperatura Alta",
        "reason_poor_connection": "Ligacao Fraca",
        "reason_fall": "Queda",
        "reason_critical_generic": "Condicao critica detetada",
        "altitude": "Altitude",
        "distance": "Distancia",
        "coordinates": "Coordenadas",
        "language_title": "Lingua",
        "language_select": "Selecionar lingua:",
        "language_current": "Atual: {language}",
        "language_apply": "Aplicar",
        "language_cancel": "Cancelar",
    },
    "es": {
        "fire_station": "Estacion de Bomberos:",
        "name_id": "Nombre/ID:",
        "nr_operationals": "N. de Operativos:",
        "login": "Iniciar sesion",
        "warning_title": "Aviso",
        "warn_select_station": "Seleccione la estacion de bomberos.",
        "warn_enter_leader_name": "Introduzca el Nombre/ID del jefe de equipo.",
        "warn_ops_integer": "El numero de operativos debe ser entero.",
        "warn_ops_between": "El numero de operativos debe estar entre 1 y 12.",
        "warn_ops_at_least_one": "Defina al menos 1 operativo.",
        "operational": "Operativos",
        "menu_edit": "Editar",
        "menu_resources": "Recursos Adicionales",
        "menu_language": "Idioma",
        "session_name": "Nombre: {name}",
        "end_session": "Finalizar sesion",
        "end_session_title": "Finalizar sesion",
        "end_session_confirm": "Desea finalizar la sesion actual?",
        "add_operational_title": "Anadir Operativo",
        "add_firefighter": "Anadir Bombero",
        "warn_max_ops": "Alcanzo el maximo de {max_ops} operativos.",
        "warn_fill_all": "Rellene todos los campos!",
        "critical_alert_title": "Alerta Critica",
        "man_down": "HOMBRE CAIDO !!!!",
        "is_down": "{name} esta caido!!",
        "reason": "Razon: {reason}",
        "view_more": "Ver Mas",
        "captain": "Capitan",
        "fire_station_value": "Estacion: {station}",
        "warnings": "Alertas",
        "no_warnings": "No hay alertas registradas.",
        "reason_hr_high": "Frecuencia cardiaca alta",
        "reason_spo2_low": "Baja oxigenacion sanguinea",
        "reason_temp_high": "Temperatura alta",
        "reason_poor_connection": "Mala conexion",
        "reason_fall": "Caida",
        "reason_critical_generic": "Condicion critica detectada",
        "altitude": "Altitud",
        "distance": "Distancia",
        "coordinates": "Coordenadas",
        "language_title": "Idioma",
        "language_select": "Seleccionar idioma:",
        "language_current": "Actual: {language}",
        "language_apply": "Aplicar",
        "language_cancel": "Cancelar",
    },
    "fr": {
        "fire_station": "Caserne:",
        "name_id": "Nom/ID:",
        "nr_operationals": "Nb d'Operateurs:",
        "login": "Connexion",
        "warning_title": "Avertissement",
        "warn_select_station": "Veuillez selectionner la caserne.",
        "warn_enter_leader_name": "Veuillez saisir le Nom/ID du chef d'equipe.",
        "warn_ops_integer": "Le nombre d'operateurs doit etre un entier.",
        "warn_ops_between": "Le nombre d'operateurs doit etre entre 1 et 12.",
        "warn_ops_at_least_one": "Definissez au moins 1 operateur.",
        "operational": "Operateurs",
        "menu_edit": "Modifier",
        "menu_resources": "Ressources Additionnelles",
        "menu_language": "Langue",
        "session_name": "Nom: {name}",
        "end_session": "Terminer Session",
        "end_session_title": "Terminer Session",
        "end_session_confirm": "Voulez-vous terminer la session en cours?",
        "add_operational_title": "Ajouter Operateur",
        "add_firefighter": "Ajouter Pompier",
        "warn_max_ops": "Maximum atteint: {max_ops} operateurs.",
        "warn_fill_all": "Remplissez tous les champs!",
        "critical_alert_title": "Alerte Critique",
        "man_down": "HOMME A TERRE !!!!",
        "is_down": "{name} est a terre!!",
        "reason": "Raison: {reason}",
        "view_more": "Voir Plus",
        "captain": "Capitaine",
        "fire_station_value": "Caserne: {station}",
        "warnings": "Alertes",
        "no_warnings": "Aucune alerte enregistree.",
        "reason_hr_high": "Rythme cardiaque eleve",
        "reason_spo2_low": "Faible oxygenation sanguine",
        "reason_temp_high": "Temperature elevee",
        "reason_poor_connection": "Mauvaise connexion",
        "reason_fall": "Chute",
        "reason_critical_generic": "Condition critique detectee",
        "altitude": "Altitude",
        "distance": "Distance",
        "coordinates": "Coordonnees",
        "language_title": "Langue",
        "language_select": "Choisir la langue:",
        "language_current": "Actuelle: {language}",
        "language_apply": "Appliquer",
        "language_cancel": "Annuler",
    },
    "de": {
        "fire_station": "Feuerwache:",
        "name_id": "Name/ID:",
        "nr_operationals": "Anzahl Einsatzkraefte:",
        "login": "Anmelden",
        "warning_title": "Warnung",
        "warn_select_station": "Bitte Feuerwache auswaehlen.",
        "warn_enter_leader_name": "Bitte Name/ID des Teamleiters eingeben.",
        "warn_ops_integer": "Die Anzahl muss eine ganze Zahl sein.",
        "warn_ops_between": "Die Anzahl muss zwischen 1 und 12 liegen.",
        "warn_ops_at_least_one": "Mindestens 1 Einsatzkraft festlegen.",
        "operational": "Einsatzkraefte",
        "menu_edit": "Bearbeiten",
        "menu_resources": "Zusaetzliche Ressourcen",
        "menu_language": "Sprache",
        "session_name": "Name: {name}",
        "end_session": "Sitzung Beenden",
        "end_session_title": "Sitzung Beenden",
        "end_session_confirm": "Moechten Sie die aktuelle Sitzung beenden?",
        "add_operational_title": "Einsatzkraft Hinzufuegen",
        "add_firefighter": "Feuerwehrmann Hinzufuegen",
        "warn_max_ops": "Maximal {max_ops} Einsatzkraefte erreicht.",
        "warn_fill_all": "Bitte alle Felder ausfuellen!",
        "critical_alert_title": "Kritischer Alarm",
        "man_down": "MANN AM BODEN !!!!",
        "is_down": "{name} ist ausgefallen!!",
        "reason": "Grund: {reason}",
        "view_more": "Mehr Anzeigen",
        "captain": "Kapitaen",
        "fire_station_value": "Feuerwache: {station}",
        "warnings": "Warnungen",
        "no_warnings": "Noch keine Warnungen registriert.",
        "reason_hr_high": "Schnelle Herzfrequenz",
        "reason_spo2_low": "Niedrige Blutsauerstoffsaettigung",
        "reason_temp_high": "Hohe Temperatur",
        "reason_poor_connection": "Schlechte Verbindung",
        "reason_fall": "Sturz",
        "reason_critical_generic": "Kritischer Zustand erkannt",
        "altitude": "Hoehe",
        "distance": "Entfernung",
        "coordinates": "Koordinaten",
        "language_title": "Sprache",
        "language_select": "Sprache auswaehlen:",
        "language_current": "Aktuell: {language}",
        "language_apply": "Anwenden",
        "language_cancel": "Abbrechen",
    },
    "it": {
        "fire_station": "Stazione Vigili del Fuoco:",
        "name_id": "Nome/ID:",
        "nr_operationals": "N. Operatori:",
        "login": "Accedi",
        "warning_title": "Avviso",
        "warn_select_station": "Seleziona la stazione dei vigili del fuoco.",
        "warn_enter_leader_name": "Inserisci Nome/ID del capo squadra.",
        "warn_ops_integer": "Il numero di operatori deve essere intero.",
        "warn_ops_between": "Il numero di operatori deve essere tra 1 e 12.",
        "warn_ops_at_least_one": "Imposta almeno 1 operatore.",
        "operational": "Operatori",
        "menu_edit": "Modifica",
        "menu_resources": "Risorse Aggiuntive",
        "menu_language": "Lingua",
        "session_name": "Nome: {name}",
        "end_session": "Termina Sessione",
        "end_session_title": "Termina Sessione",
        "end_session_confirm": "Vuoi terminare la sessione corrente?",
        "add_operational_title": "Aggiungi Operatore",
        "add_firefighter": "Aggiungi Pompiere",
        "warn_max_ops": "Raggiunto il massimo di {max_ops} operatori.",
        "warn_fill_all": "Compila tutti i campi!",
        "critical_alert_title": "Allerta Critica",
        "man_down": "UOMO A TERRA !!!!",
        "is_down": "{name} e a terra!!",
        "reason": "Motivo: {reason}",
        "view_more": "Vedi Dettagli",
        "captain": "Capitano",
        "fire_station_value": "Stazione: {station}",
        "warnings": "Avvisi",
        "no_warnings": "Nessun avviso registrato.",
        "reason_hr_high": "Frequenza cardiaca alta",
        "reason_spo2_low": "Bassa ossigenazione del sangue",
        "reason_temp_high": "Temperatura alta",
        "reason_poor_connection": "Connessione scarsa",
        "reason_fall": "Caduta",
        "reason_critical_generic": "Condizione critica rilevata",
        "altitude": "Altitudine",
        "distance": "Distanza",
        "coordinates": "Coordinate",
        "language_title": "Lingua",
        "language_select": "Seleziona lingua:",
        "language_current": "Corrente: {language}",
        "language_apply": "Applica",
        "language_cancel": "Annulla",
    },
}


def translate(language_code, key, **kwargs):
    lang_map = TRANSLATIONS.get(language_code, {})
    base_map = TRANSLATIONS["en"]
    text = lang_map.get(key, base_map.get(key, key))
    if kwargs:
        try:
            return text.format(**kwargs)
        except (KeyError, ValueError):
            return text
    return text


def get_language_label(language_code):
    for label, code in LANGUAGE_OPTIONS:
        if code == language_code:
            return label
    return language_code

