TDMA_SLOT_DURATION_MS = 100
TDMA_FRAME_SLOTS = 32
TDMA_FRAME_DURATION_MS = TDMA_SLOT_DURATION_MS * TDMA_FRAME_SLOTS

TDMA_UPLINK_SLOT_START = 0
TDMA_UPLINK_SLOT_END = 19
TDMA_CTRL_SLOT_START = 20
TDMA_CTRL_SLOT_END = 29
TDMA_GUARD_SLOT_START = 30
TDMA_GUARD_SLOT_END = 31

TDMA_RX_GUARD_BEFORE_MS = 5
TDMA_RX_GUARD_AFTER_MS = 5


def tdma_ctrl_slot_for_vest(vest_id):
    return TDMA_CTRL_SLOT_START + (int(vest_id) % 10)


def tdma_uplink_slot_for_vest(vest_id):
    return int(vest_id) % 20
